name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-ci:
    name: Terraform CI Pipeline
    runs-on: ubuntu-latest

    steps:
      # Checkout o código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      # Configurar credenciais AWS (apenas leitura para testes)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Inicializar o Terraform
      - name: Terraform Init
        run: terraform init

      # Validar o Terraform
      - name: Terraform Validate
        run: terraform validate

      # Verificar erros de sintaxe no código Terraform
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Gerar o Plano do Terraform (sem salvar)
      - name: Terraform Plan
        run: terraform plan

      # Opcional: Adicionar um Job para Linting do Terraform
      - name: Terraform Lint
        uses: actionshub/terraform-lint@v1.0.0
