name: Terraform CI/CD

on:
  push:
    branches:
      - main 
#   pull_request:
#     branches:
#       - main

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    steps:
      # Checkout o código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      # Configurar credenciais AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Inicializar o Terraform
      - name: Terraform Init
        run: terraform init

      #  Verificar a formatação
      - name: Terraform Fmt
        run: terraform fmt -check

      # Validar o Terraform
      - name: Terraform Validate
        run: terraform validate

      # Gerar o Plano
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Salvar o Plano para Revisão
      - name: Save Terraform Plan Output
        run: terraform show -json tfplan > tfplan.json

      # Aplicar o Plano (apenas na branch main)
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan